<?php

namespace App\Http\Controllers\HT11;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\HT11\FormInsurance;
class InsuranceReportController extends Controller
{
    public function index(){
        return view('insurance.report');// TODO: Change the autogenerated stub
    }
    public function show($id)
    {
        return FormInsurance::join('ht11_insurance', 'ht11_insurance.id', '=', 'ht11_form_insurances.type')->where("ht11_form_insurances.id",$id)->get(['ht11_form_insurances.*','ht11_insurance.name as group','ht11_insurance.form as form']);
    }
}
